config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Create new task
  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'
  # Update task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  # Show all
  get 'tasks', to: 'tasks#index', as: :all_tasks
  # Display one
  get 'tasks/:id', to: 'tasks#show', as: :task
  # Delete
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(strong_params)
    @task.save
    redirect_to tasks_path(@tasks)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(strong_params)
    redirect_to tasks_path(@tasks)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path(@tasks)
  end

  def strong_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f|%>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Update <%= "#{@task.title}" %></h1>
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<ul>
<h1>My tasks</h1>
 <% @tasks.each do |task| %>
  <li>
    <%= link_to "#{task.title}", task_path(task) %>
    <%= link_to "🗑",
    task_path(task), method: :delete, data: { confirm: "Are you sure you want to delete #{task.title}? "} %>

  </li>
 <% end  %>
</ul>
<p> <%= link_to "Add a new task", new_task_path %></p>

app/views/tasks/new.html.erb
<h1>Create a new Task</h1>
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h2> <%= @task.title %></h2>
<p> <%= @task.details %></p>
<p> <%= link_to "Delete #{@task.title}",
    task_path(@task), method: :delete,
    data: { confirm: "Are you sure you want to delete #{@task.title}? "} %> </p>
<p> <%= link_to "See all tasks", tasks_path(@tasks) %> </p>
<p> <%= link_to "Edit #{@task.title}", edit_task_path(@task) %></p>